alias tls='tmux ls'
alias tns='tmux new-session -s'
alias tas='tmux attach-session -t'
alias tks='tmux kill-session -t'
alias vpn='sudo /home/linuxbrew/.linuxbrew/bin/openfortivpn 0.0.0.0'
alias config='git --git-dir=/home/charles/.dotfiles/ --work-tree=/home/charles/'
